version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api1
    depends_on:
      - mongodb
    build: 
      context: server
      dockerfile: ./dockerfile
    ports:
      - 5000:5000

  ui:
    image: ui1
    depends_on:
      - api
    build:
      context: Ui
      dockerfile: ./dockerfile
    ports:
      - 5173:5173

volumes:
  mongo_volume: